version: "3"
services:
  node-app:
    build: .
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=connerf
      - MONGO_INITDB_ROOT_PASSWORD=pw123
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: